### ISSUE TITLE
Multi line env vars continued

### ISSUE THREAD

**Issue by aahnik** [digitalocean/sample-django#10]
hi @kamaln7 with regards to #9 

> I'll close this ticket for now but please feel free to re-open if this still doesn't work for you.

Github does not allow me to re-open an issue that you closed. So, I opened a new one.

Please see my comment https://github.com/digitalocean/sample-django/issues/9#issuecomment-860150504

Multi-line env var is such a basic thing (so many things can have multi-line values), and I am surprised that DO does not support it. Am I doing something wrong ?

**Comment by kamaln7** [comment]
Hi @aahnik, sorry about the confusion with the other issue being closed. I've re-opened it and will close this one. We'll take a closer look at this and get back to you.
