### ISSUE TITLE
Not Clear on how to use static files via Digital Ocean App Platform

### ISSUE THREAD

**Issue by aplusclients** [digitalocean/sample-django#3]
It was not clear on how to use static files via Digital Ocean App Platform, the YouTube video attached to this sample project is not clear about static files specifically.  I thought that the DO Spaces or static sites were required but I have been able to get them working simply using white noise.  Perhaps a follow up video will be useful.  In the past I have used NGINX so I am not exactly sure how the Digital Ocean APP Platform is handling this.  I am also curious still about how to connect static files using Digital Oceans CDN.

Would it require something like the following settings and environment variable?:

```py
STATIC_HOST = os.environ.get('DJANGO_STATIC_HOST', '')
STATIC_URL = STATIC_HOST + '/static/'

DJANGO_STATIC_HOST=??
```

-------------------------------
**UPDATE** To anyone interested I was able to get static files working using whitenoise and making sure the middleware and settings are as follows.  And also making sure that collectstatic is not disabled or =1 on the DO App Platform.  

```py
'whitenoise.middleware.WhiteNoiseMiddleware',

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
```

**Comment by kamaln7** [comment]
Hi @aplusclients,

There are two ways to achieve this on App Platform. One is like you figured out — to use whitenoise and have the Django webserver serve the static files. The other way is to use a Static Site component for the static sites. Static Site components are included in the cost of dynamic apps so it won't cost extra.

The difference is that with the static site component, the static files will be served directly from the App Platform CDN without hitting your Django app. Whereas if you serve them using whitenoise/Django, the requests for static files will still go to the CDN, but the CDN will then request them from Django. For more info on the Static Site component approach, please see the tutorial [How To Deploy a Django App on App Platform](https://www.digitalocean.com/community/tutorials/how-to-deploy-django-to-app-platform).

Both approaches are valid. If you choose to use whitenoise to serve static files, I strongly recommend configuring whitenoise to set proper `Cache-Control` headers to ensure that the assets are cached on users' browsers and/or on the CDN layer.

I'm marking this issue as closed but please let me know if you have any questions.
